HEIGHT = 50
WIDTH = 1500

SKY_HEIGHT = 3
GROUND_HEIGHT = 45

MANDO_SIZE = [4,2]
#MANDO_INIT_LOCATION = [GROUND_HEIGHT - 1, 1]
MANDO_INIT_LOCATION = [GROUND_HEIGHT - 1, WIDTH - 164]
MANDO_LIVES = 4

MANDO_BULLET_SIZE = [1, 2]
BOSS_BULLET_SIZE = [7, 1]

BOSS_SIZE = [7, 7]
BOSS_INIT_LOCATION = [GROUND_HEIGHT - 1, WIDTH - 1 - BOSS_SIZE[1]]
BOSS_LIVES = 5

COIN_SIZE = [4, 4]
COINB_COUNT = 20

HLAZER_SIZE = [1, 8]
HLAZER_COUNT = 15

VLAZER_SIZE = [8, 1]
VLAZER_COUNT = 15

DLAZER_SIZE = [8, 8]
DLAZER_COUNT = 10

MAGNET_SIZE = [2, 2]
MAGNET_COUNT = 2

RANDOM_OBJECT_COUNT = COINB_COUNT + HLAZER_COUNT + VLAZER_COUNT + DLAZER_COUNT + MAGNET_COUNT